  import type { Metadata } from "next";
  import { Nunito,Karla,Poppins } from "next/font/google";
  import Nav from "./components/nav";
  import "./globals.css";
import SessionWrapper from "./SessionWrapper";

  const nunito = Nunito({
    variable: "--font-Nunito",
    subsets: ["latin"],
    weight: ["200", "300", "500", "600"],
  });
  const pop = Poppins({
    variable: "--font-Poppins",
    subsets: ["latin"],
    weight: [ "100","200","500", "300", "700"],
  });

  const karl = Karla({
    variable: "--font-karla",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
  });


  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en" >
        <body className={`${nunito.variable} ${karl.variable} ${pop.variable} bg-[#1D1616]`} >
          <SessionWrapper>
          <Nav/>
           {children}
           </SessionWrapper>

          
        </body>
      </html>
    );
  }
